blank_issues_enabled: false
contact_links:
  - name: ğŸ¤ General Questions or Help
    url: https://github.com/Sajad-2099/VITA/discussions
    about: Ask questions, get help, or discuss anything not related to a specific bug or feature.

